// src/context/LanguageContext.jsx
import React, { createContext, useContext, useEffect, useState } from "react";

const LanguageContext = createContext();

const TRANSLATIONS = {
  en: {
    // EXISTING TRANSLATIONS (keep these)
    appName: "Agro Suvidha",
    stepText: "Step 1 of 2",
    greeting: "Namaste",
    chooseLang: "Choose Your Language",
    chooseLangDesc: "Select your preferred language to continue",
    continueBtn: "Continue",
    helpText: "You can change this later in settings",
    footerText: "Smart Farming. Smarter Future.",

    // NEW MANDI PRICE TRANSLATIONS
    smartCropAdvisory: "Smart Crop Advisory - Live Data",
    realTimePrices: "Real-time mandi prices and profit analysis",
    marketPriceCalc: "Market Price Calculator",
    calcProfitMargins: "Calculate your best profit margins",
    live: "LIVE",
    inputParameters: "INPUT PARAMETERS",
    cropType: "Crop Type",
    quantity: "Quantity",
    quintals: "quintals",
    transportCost: "Transport Cost",
    rupeesPerKm: "₹/km",
    bestCropVoice: "Best Crop Voice Advice",
    audioSummary: "Audio summary for the best mandi and crop.",
    locationDetected: "Location Detected Successfully",
    landrumPunjab: "Landrum, Punjab",
    getMandiPrices: "GET MANDI PRICES",
    fetching: "Fetching...",
    geoNotSupported: "Geolocation not supported by your browser.",
    locationFailed: "Location detection failed. Please allow location access.",
    detectLocationFirst: "Please detect your location first.",
    enterCropName: "Enter a crop name.",
    quantityPositive: "Quantity must be a positive number.",
    transportNotNegative: "Transport cost cannot be negative.",
    fetchError: "Error fetching prices",
    serverError: "Server error",
    back: "Back to Dashboard",
    error: "Error",
    resultsAppearHere: "Results will appear here",
    clickGetPrices: 'Click "Get Mandi Prices" to view recommendations',
    bestMandiRec: "Best Mandi Recommendation",
    mostProfitable: "Most Profitable",
    pricePerQuintal: "₹ Price/Quintal",
    distance: "Distance",
    km: "km",
    netProfit: "Net Profit",
    profitability: "Profitability",
    expectedRevenue: "Expected Revenue",
    for: "for",
    quintalsOf: "quintals of",
    recommendedMaxProfit: "Recommended for maximum profit with optimal distance",
    tableView: "Table View",
    mapView: "Map View",
    allMandis: "All Mandis",
    rank: "Rank",
    mandiName: "Mandi Name",
    priceQuintal: "Price/Quintal",
    westBengal: "West Bengal",
    mandiLocationsMap: "Mandi Locations Map",
    yourLocation: "Your Location",
    bestMandi: "Best Mandi",
    otherMandis: "Other Mandis",
    you: "You",
    mandiDetails: "Mandi Details",
    coordinates: "Coordinates",
    selectMandiMarker: "Select a mandi marker on the map.",
    marketInsights: "Market Insights",
    avgMarketPrice: "Avg. Market Price",
    transportEfficiency: "Transport Efficiency",
    profitMargin: "Profit Margin",
    excellent: "Excellent"
  },
  hi: {
    // EXISTING TRANSLATIONS (keep these)
    appName: "एग्रो सुविधा",
    stepText: "कदम 1 में से 2",
    greeting: "नमस्ते",
    chooseLang: "अपनी भाषा चुनें",
    chooseLangDesc: "जारी रखने के लिए अपनी पसंदीदा भाषा चुनें",
    continueBtn: "आगे बढ़ें",
    helpText: "आप इसे बाद में सेटिंग्स में बदल सकते हैं",
    footerText: "स्मार्ट खेती। स्मार्ट भविष्य।",

    // NEW MANDI PRICE TRANSLATIONS
    smartCropAdvisory: "स्मार्ट फसल सलाह - लाइव डेटा",
    realTimePrices: "रीयल-टाइम मंडी दरें और लाभ विश्लेषण",
    marketPriceCalc: "मंडी मूल्य कैलकुलेटर",
    calcProfitMargins: "अपने सर्वश्रेष्ठ लाभ मार्जिन की गणना करें",
    live: "लाइव",
    inputParameters: "इनपुट पैरामीटर",
    cropType: "फसल प्रकार",
    quantity: "मात्रा",
    quintals: "क्विंटल",
    transportCost: "परिवहन लागत",
    rupeesPerKm: "₹/किमी",
    bestCropVoice: "सर्वश्रेष्ठ फसल वॉइस सलाह",
    audioSummary: "सर्वश्रेष्ठ मंडी और फसल का ऑडियो सारांश।",
    locationDetected: "स्थान सफलतापूर्वक पता लगाया गया",
    landrumPunjab: "लैंड्रम, पंजाब",
    getMandiPrices: "मंडी दरें प्राप्त करें",
    fetching: "लाया जा रहा है...",
    geoNotSupported: "आपके ब्राउज़र द्वारा जियोलोकेशन समर्थित नहीं है।",
    locationFailed: "स्थान पता लगाने में विफल। कृपया स्थान एक्सेस की अनुमति दें।",
    detectLocationFirst: "कृपया पहले अपना स्थान पता लगाएं।",
    enterCropName: "फसल का नाम दर्ज करें।",
    quantityPositive: "मात्रा धनात्मक संख्या होनी चाहिए।",
    transportNotNegative: "परिवहन लागत ऋणात्मक नहीं हो सकती।",
    fetchError: "दरें लाने में त्रुटि",
    serverError: "सर्वर त्रुटि",
    back: "डैशबोर्ड पर वापस",
    error: "त्रुटि",
    resultsAppearHere: "परिणाम यहाँ दिखाई देंगे",
    clickGetPrices: '"मंडी दरें प्राप्त करें" पर क्लिक करें सिफारिशें देखने के लिए',
    bestMandiRec: "सर्वश्रेष्ठ मंडी सिफारिश",
    mostProfitable: "सबसे लाभदायक",
    pricePerQuintal: "₹ प्रति क्विंटल मूल्य",
    distance: "दूरी",
    km: "किमी",
    netProfit: "शुद्ध लाभ",
    profitability: "लाभप्रदता",
    expectedRevenue: "अपेक्षित राजस्व",
    for: "के लिए",
    quintalsOf: "क्विंटल",
    recommendedMaxProfit: "सर्वाधिक लाभ के लिए अनुशंसित",
    tableView: "तालिका दृश्य",
    mapView: "मानचित्र दृश्य",
    allMandis: "सभी मंडियाँ",
    rank: "रैंक",
    mandiName: "मंडी का नाम",
    priceQuintal: "प्रति क्विंटल मूल्य",
    westBengal: "पश्चिम बंगाल",
    mandiLocationsMap: "मंडी स्थान मानचित्र",
    yourLocation: "आपका स्थान",
    bestMandi: "सर्वश्रेष्ठ मंडी",
    otherMandis: "अन्य मंडियाँ",
    you: "आप",
    mandiDetails: "मंडी विवरण",
    coordinates: "निर्देशांक",
    selectMandiMarker: "मानचित्र पर मंडी मार्कर चुनें।",
    marketInsights: "बाजार अंतर्दृष्टि",
    avgMarketPrice: "औसत बाजार मूल्य",
    transportEfficiency: "परिवहन दक्षता",
    profitMargin: "लाभ मार्जिन",
    excellent: "उत्कृष्ट"
  },
  bn: {
    // EXISTING TRANSLATIONS (keep these)
    appName: "এগ্রো সুবিধা",
    stepText: "পদক্ষেপ ১ এর মধ্যে ২",
    greeting: "নমস্কার",
    chooseLang: "আপনার ভাষা নির্বাচন করুন",
    chooseLangDesc: "চালিয়ে যেতে আপনার পছন্দের ভাষা নির্বাচন করুন",
    continueBtn: "চালিয়ে যান",
    helpText: "আপনি পরে সেটিংসে এটি পরিবর্তন করতে পারবেন",
    footerText: "স্মার্ট চাষাবাদ। স্মার্ট ভবিষ্যৎ।",

    // NEW MANDI PRICE TRANSLATIONS
    smartCropAdvisory: "স্মার্ট ফসল উপদেশ - লাইভ ডেটা",
    realTimePrices: "রিয়েল-টাইম মণ্ডি দর এবং লাভ বিশ্লেষণ",
    marketPriceCalc: "মণ্ডি মূল্য ক্যালকুলেটর",
    calcProfitMargins: "আপনার সেরা লাভ মার্জিন গণনা করুন",
    live: "লাইভ",
    inputParameters: "ইনপুট প্যারামিটার",
    cropType: "ফসলের ধরন",
    quantity: "পরিমাণ",
    quintals: "কুইন্টাল",
    transportCost: "পরিবহন খরচ",
    rupeesPerKm: "₹/কিমি",
    bestCropVoice: "সেরা ফসল ভয়েস পরামর্শ",
    audioSummary: "সেরা মণ্ডি এবং ফসলের অডিও সারাংশ।",
    locationDetected: "অবস্থান সফলভাবে শনাক্ত হয়েছে",
    landrumPunjab: "ল্যান্ড্রাম, পাঞ্জাব",
    getMandiPrices: "মণ্ডি দর পান",
    fetching: "আনা হচ্ছে...",
    geoNotSupported: "আপনার ব্রাউজারে জিওলোকেশন সমর্থিত নয়।",
    locationFailed: "অবস্থান শনাক্তকরণ ব্যর্থ। দয়া করে অবস্থান অ্যাক্সেসের অনুমতি দিন।",
    detectLocationFirst: "দয়া করে আগে আপনার অবস্থান শনাক্ত করুন।",
    enterCropName: "ফসলের নাম লিখুন।",
    quantityPositive: "পরিমাণ ধনাত্মক সংখ্যা হতে হবে।",
    transportNotNegative: "পরিবহন খরচ ঋণাত্মক হতে পারে না।",
    fetchError: "দর আনতে ত্রুটি",
    serverError: "সার্ভার ত্রুটি",
    back: "ড্যাশবোর্ডে ফিরুন",
    error: "ত্রুটি",
    resultsAppearHere: "ফলাফল এখানে দেখাবে",
    clickGetPrices: '"মণ্ডি দর পান" ক্লিক করুন সুপারিশ দেখতে',
    bestMandiRec: "সেরা মণ্ডি সুপারিশ",
    mostProfitable: "সবচেয়ে লাভজনক",
    pricePerQuintal: "₹ প্রতি কুইন্টাল মূল্য",
    distance: "দূরত্ব",
    km: "কিমি",
    netProfit: "নেট লাভ",
    profitability: "লাভজনকতা",
    expectedRevenue: "আশা করা আয়",
    for: "এর জন্য",
    quintalsOf: "কুইন্টাল",
    recommendedMaxProfit: "সর্বোচ্চ লাভের জন্য সুপারিশকৃত",
    tableView: "টেবিল দৃশ্য",
    mapView: "মানচিত্র দৃশ্য",
    allMandis: "সকল মণ্ডি",
    rank: "র্যাঙ্ক",
    mandiName: "মণ্ডির নাম",
    priceQuintal: "প্রতি কুইন্টাল মূল্য",
    westBengal: "পশ্চিমবঙ্গ",
    mandiLocationsMap: "মণ্ডি অবস্থান মানচিত্র",
    yourLocation: "আপনার অবস্থান",
    bestMandi: "সেরা মণ্ডি",
    otherMandis: "অন্যান্য মণ্ডি",
    you: "আপনি",
    mandiDetails: "মণ্ডি বিবরণ",
    coordinates: "স্থানাংক",
    selectMandiMarker: "মানচিত্রে মণ্ডি মার্কার নির্বাচন করুন।",
    marketInsights: "বাজার অন্তর্দৃষ্টি",
    avgMarketPrice: "গড় বাজার মূল্য",
    transportEfficiency: "পরিবহন দক্ষতা",
    profitMargin: "লাভ মার্জিন",
    excellent: "উত্কৃষ্ট"
  },
  pa: {
    // EXISTING TRANSLATIONS (keep these)
    appName: "ਐਗਰੋ ਸੁਵਿਧਾ",
    stepText: "ਕਦਮ 1 ਵਿਚੋਂ 2",
    greeting: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
    chooseLang: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    chooseLangDesc: "ਜਾਰੀ ਰੱਖਣ ਲਈ ਆਪਣੀ ਮਨਪਸੰਦ ਭਾਸ਼ਾ ਚੁਣੋ",
    continueBtn: "ਜਾਰੀ ਰੱਖੋ",
    helpText: "ਤੁਸੀਂ ਇਸਨੂੰ ਬਾਅਦ ਵਿੱਚ ਸੈਟਿੰਗਜ਼ ਵਿੱਚ ਬਦਲ ਸਕਦੇ ਹੋ",
    footerText: "ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ। ਸਮਾਰਟ ਭਵਿੱਖ।",

    // NEW MANDI PRICE TRANSLATIONS
    smartCropAdvisory: "ਸਮਾਰਟ ਫਸਲ ਸਲਾਹ - ਲਾਈਵ ਡੇਟਾ",
    realTimePrices: "ਰੀਅਲ-ਟਾਈਮ ਮੰਡੀ ਦਰਾਂ ਅਤੇ ਲਾਭ ਵਿਸ਼ਲੇਸ਼ਣ",
    marketPriceCalc: "ਮੰਡੀ ਕੀਮਤ ਕੈਲਕੂਲੇਟਰ",
    calcProfitMargins: "अपਣੇ ਸਭ ਤੋਂ ਵਧੀਆ ਲਾਭ ਮਾਰਜਿਨ ਦੀ ਗਣਨਾ ਕਰੋ",
    live: "ਲਾਈਵ",
    inputParameters: "ਇਨਪੁਟ ਪੈਰਾਮੀਟਰ",
    cropType: "ਫਸਲ ਪ੍ਰਕਾਰ",
    quantity: "ਮਾਤਰਾ",
    quintals: "ਕੁਇੰਟਲ",
    transportCost: "ਕਾਰਵਾਹੀ ਲਾਗਤ",
    rupeesPerKm: "₹/ਕਿਲੋਮੀਟਰ",
    bestCropVoice: "ਸਭ ਤੋਂ ਵਧੀਆ ਫਸਲ ਵਾਇਸ ਸਲਾਹ",
    audioSummary: "ਸਭ ਤੋਂ ਵਧੀਆ ਮੰਡੀ ਅਤੇ ਫਸਲ ਦਾ ਆਡੀਓ ਸਾਰਾਂਸ਼।",
    locationDetected: "ਸਥਾਨ ਸਫਲਤਾਪੂਰਵਕ ਪਤਾ ਲਗਾਇਆ ਗਿਆ",
    landrumPunjab: "ਲੈਂਡਰਮ, ਪੰਜਾਬ",
    getMandiPrices: "ਮੰਡੀ ਦਰਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    fetching: "ਲਿਆਂਦਾ ਜਾ ਰਿਹਾ ਹੈ...",
    geoNotSupported: "ਤੁਹਾਡੇ ਬ੍ਰਾਊਜ਼ਰ ਵੱਲੋਂ ਜੀਓਲੋਕੇਸ਼ਨ ਸਮਰਥਿਤ ਨਹੀਂ ਹੈ।",
    locationFailed: "ਸਥਾਨ ਪਤਾ ਲਗਾਉਣ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਸਥਾਨ ਪਹੁੰਚ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ।",
    detectLocationFirst: "ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਆਪਣਾ ਸਥਾਨ ਪਤਾ ਲਗਾਓ।",
    enterCropName: "ਫਸਲ ਦਾ ਨਾਮ ਦਾਖਲ ਕਰੋ।",
    quantityPositive: "ਮਾਤਰਾ ਧਨਾਤਮਕ ਅੰਕ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ।",
    transportNotNegative: "ਕਾਰਵਾਹੀ ਲਾਗਤ ਋ਣਾਤਮਕ ਨਹੀਂ ਹੋ ਸਕਦੀ।",
    fetchError: "ਦਰਾਂ ਲਿਆਉਣ ਵਿੱਚ ਗਲਤੀ",
    serverError: "ਸਰਵਰ ਗਲਤੀ",
    back: "ਡੈਸ਼ਬੋਰਡ ਤੇ ਵਾਪਸ",
    error: "ਗਲਤੀ",
    resultsAppearHere: "ਫਲਤਾਂ ਇੱਥੇ ਦਿਖਾਈਆਂ ਜਾਣਗੀਆਂ",
    clickGetPrices: '"ਮੰਡੀ ਦਰਾਂ ਪ੍ਰਾਪਤ ਕਰੋ" ਤੇ ਕਲਿੱਕ ਕਰੋ ਸਿਫ਼ਾਰਸ਼ਾਂ ਵੇਖਣ ਲਈ',
    bestMandiRec: "ਸਭ ਤੋਂ ਵਧੀਆ ਮੰਡੀ ਸਿਫ਼ਾਰਸ਼",
    mostProfitable: "ਸਭ ਤੋਂ ਲਾਭਕਾਰੀ",
    pricePerQuintal: "₹ ਪ੍ਰਤੀ ਕੁਇੰਟਲ ਕੀਮਤ",
    distance: "ਦੂਰੀ",
    km: "ਕਿਲੋਮੀਟਰ",
    netProfit: "ਨੈੱਟ ਲਾਭ",
    profitability: "ਲਾਭਕਾਰੀਤਾ",
    expectedRevenue: "ਉਮੀਦਵਾਰ ਆਮਦਨ",
    for: "ਲਈ",
    quintalsOf: "ਕੁਇੰਟਲ",
    recommendedMaxProfit: "ਸਰਵੋਚਚ ਲਾਭ ਲਈ ਸਿਫ਼ਾਰਸ਼ੀ",
    tableView: "ਟੇਬਲ ਵਿਊ",
    mapView: "ਮੈਪ ਵਿਊ",
    allMandis: "ਸਾਰੀਆਂ ਮੰਡੀਆਂ",
    rank: "ਰੈਂਕ",
    mandiName: "ਮੰਡੀ ਦਾ ਨਾਮ",
    priceQuintal: "ਪ੍ਰਤੀ ਕੁਇੰਟਲ ਕੀਮਤ",
    westBengal: "ਪੱਛਮੀ ਬੰਗਾਲ",
    mandiLocationsMap: "ਮੰਡੀ ਸਥਾਨ ਮੈਪ",
    yourLocation: "ਤੁਹਾਡਾ ਸਥਾਨ",
    bestMandi: "ਸਭ ਤੋਂ ਵਧੀਆ ਮੰਡੀ",
    otherMandis: "ਹੋਰ ਮੰਡੀਆਂ",
    you: "ਤੁਸੀਂ",
    mandiDetails: "ਮੰਡੀ ਵੇਰਵੇ",
    coordinates: "ਅਕਸ",
    selectMandiMarker: "ਮੈਪ ਤੇ ਮੰਡੀ ਮਾਰਕਰ ਚੁਣੋ।",
    marketInsights: "ਬਜ਼ਾਰ ਇਨਸਾਈਟਸ",
    avgMarketPrice: "ਔਸਤ ਬਜ਼ਾਰ ਕੀਮਤ",
    transportEfficiency: "ਕਾਰਵਾਹੀ ਕੁਸ਼ਲਤਾ",
    profitMargin: "ਲਾਭ ਮਾਰਜਿਨ",
    excellent: "ਉੱਤਮ"
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("agro_language");
    return saved || "hi"; // Default to Hindi for farmers
  });

  useEffect(() => {
    localStorage.setItem("agro_language", language);
  }, [language]);

  function t(key) {
    const pack = TRANSLATIONS[language] || TRANSLATIONS.en;
    return pack[key] ?? key;
  }

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        translations: TRANSLATIONS,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
